#pragma once

#define ALL_COMPONENT_MACRO(MACRO)\
MACRO(Engine::Editor::UI, ColorGradientEditorComponent)\
MACRO(Engine::Editor::UI, ColorPickerEditorComponent)\
MACRO(Engine::UI, UIButtonComponent)\
MACRO(Engine::UI, UIInputFieldComponent)\
MACRO(Engine::UI, UILayoutComponent)\
MACRO(Engine::UI, UIPanelComponent)\
MACRO(Engine::UI, UIRendererComponent)\
MACRO(Engine::UI, UISelectableComponent)\
MACRO(Engine::UI, UISliderComponent)\
MACRO(Engine::UI, UITextComponent)\
MACRO(Engine::UI, UITextureComponent)\
MACRO(Engine::UI, UIToggleComponent)\
MACRO(Engine::UI, UITransformComponent)\
MACRO(Engine::Animation, AnimatorComponent)\
MACRO(Engine::Animation, SpriteAnimatorComponent)\
MACRO(Engine::Camera, CameraComponent)\
MACRO(Engine::ECS, EntityData)\
MACRO(Engine::Input, InputComponent)\
MACRO(Engine::Lighting2D, LightSource2DComponent)\
MACRO(Engine::Lighting3D, PointLight3DComponent)\
MACRO(Engine::ParticleSystem, ParticleEmitterComponent)\
MACRO(Engine::Physics, CollisionBoxComponent)\
MACRO(Engine::Physics, PhysicsBodyComponent)\
MACRO(Engine::Player, PlayerComponent)\
MACRO(Engine::Rendering, EntityRenderer2DComponent)\
MACRO(Engine::Rendering, Mesh3DComponent)\
MACRO(Engine, TestComponent)\
MACRO(Engine, TransformComponent)\
MACRO(Engine::World, TriggerComponent)\
        
#define EDITOR_COMPONENT_MACRO(MACRO)\
MACRO(Engine::Editor::UI, ColorGradientEditorComponent)\
MACRO(Engine::Editor::UI, ColorPickerEditorComponent)\
        
#define UI_COMPONENT_MACRO(MACRO)\
MACRO(Engine::UI, UIButtonComponent)\
MACRO(Engine::UI, UIInputFieldComponent)\
MACRO(Engine::UI, UILayoutComponent)\
MACRO(Engine::UI, UIPanelComponent)\
MACRO(Engine::UI, UIRendererComponent)\
MACRO(Engine::UI, UISelectableComponent)\
MACRO(Engine::UI, UISliderComponent)\
MACRO(Engine::UI, UITextComponent)\
MACRO(Engine::UI, UITextureComponent)\
MACRO(Engine::UI, UIToggleComponent)\
MACRO(Engine::UI, UITransformComponent)\
        
#define WORLD_COMPONENT_MACRO(MACRO)\
MACRO(Engine::Animation, AnimatorComponent)\
MACRO(Engine::Animation, SpriteAnimatorComponent)\
MACRO(Engine::Camera, CameraComponent)\
MACRO(Engine::ECS, EntityData)\
MACRO(Engine::Input, InputComponent)\
MACRO(Engine::Lighting2D, LightSource2DComponent)\
MACRO(Engine::Lighting3D, PointLight3DComponent)\
MACRO(Engine::ParticleSystem, ParticleEmitterComponent)\
MACRO(Engine::Physics, CollisionBoxComponent)\
MACRO(Engine::Physics, PhysicsBodyComponent)\
MACRO(Engine::Player, PlayerComponent)\
MACRO(Engine::Rendering, EntityRenderer2DComponent)\
MACRO(Engine::Rendering, Mesh3DComponent)\
MACRO(Engine, TestComponent)\
MACRO(Engine, TransformComponent)\
MACRO(Engine::World, TriggerComponent)\
